name: task_sense
description: "A demo Flutter application that combines task management with real-time sensor tracking, featuring a To-Do List with alerts and dynamic gyroscope and accelerometer data monitoring."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # for fonts
  google_fonts: ^6.2.1
  # service locator
  get_it: ^8.0.0
  # Value equality
  equatable: ^2.0.5
  # Functional programming things
  dartz: ^0.10.1
  # for state management
  flutter_bloc: ^8.1.6
  # for easy animation
  flutter_animate: ^4.5.0

  # for local database
  sqflite: ^2.3.3+1
  path: 1.9.0 # do not change it pinned
  path_provider: ^2.1.4

  # for route management
  go_router: ^14.3.0
  # for localization
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  # for different flavor integration
  flutter_flavorizr: ^2.2.3

  # for test
  mockito: ^5.4.4
  #test: ^1.25.8
  build_runner: ^2.4.11
  bloc_test: ^9.1.7

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/languages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
