// Mocks generated by Mockito 5.4.4 from annotations
// in task_sense/test/features/sensor_tracker/presentation/blocs/acceletor_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:task_sense/core/use_cases/use_case.dart' as _i6;
import 'package:task_sense/features/sensor_tracker/domain/entities/sensor.dart'
    as _i5;
import 'package:task_sense/features/sensor_tracker/domain/repositories/sensor_repository.dart'
    as _i2;
import 'package:task_sense/features/sensor_tracker/domain/use_cases/get_accelerometer_data.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSensorRepository_0 extends _i1.SmartFake
    implements _i2.SensorRepository {
  _FakeSensorRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAccelerometerData].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAccelerometerData extends _i1.Mock
    implements _i3.GetAccelerometerData {
  MockGetAccelerometerData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SensorRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSensorRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SensorRepository);

  @override
  _i4.Stream<_i5.SensorEntity> call({required _i6.NoParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i4.Stream<_i5.SensorEntity>.empty(),
      ) as _i4.Stream<_i5.SensorEntity>);
}
