///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsAddTask = 'assets/icons/add_task.png';
  static const String iconsLogo = 'assets/icons/logo.png';
  static const String iconsSearch = 'assets/icons/search.png';
  static const String imagesProfile = 'assets/images/profile.png';
  static const String languagesEn = 'assets/languages/en.json';
}
